### ISSUE TITLE
Upgrade to latest (2.67), it works

### ISSUE THREAD

**Issue by marcosgm** [lacework/terraform-azure-config#17]
https://github.com/lacework/terraform-azure-config/blob/6a2b13f1e562d45f0a8196b31b566d0b195cde93/versions.tf#L6

As explained in https://github.com/lacework/terraform-azure-activity-log/issues/21, I would suggest having the module refer to minimum v2.28, but in this main module I'd go with latest  2.67 (which I just tested and it works fine) https://registry.terraform.io/providers/hashicorp/azurerm/2.67.0/docs/resources/role_assignment

**Comment by afiune** [comment]
https://lacework.atlassian.net/browse/ALLY-588
